name: Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Theos
        uses: theos/setup-theos@main
        with:
          sdk: iphoneos15.0

      - name: Build
        run: make clean && make

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: .theos/obj/*.dylib
